use std::fs;
use std::io::Write;
use std::path::Path;

use anyhow::{bail, Result};
use zetteltex_core::WorkspacePaths;

use crate::i18n::{set_lang, tr, Lang};

const TEMPLATE_NOTE: &str = include_str!("../../../template/note.tex");
const TEMPLATE_PROJECT: &str = include_str!("../../../template/project.tex");
const TEMPLATE_STYLE: &str = include_str!("../../../template/style.sty");
const TEMPLATE_TEXBOOK: &str = include_str!("../../../template/texbook.cls");
const TEMPLATE_TEXNOTE: &str = include_str!("../../../template/texnote.cls");
const CONFIG_TOML_ES: &str = r#"# Configuración de ZettelTeX
# Este archivo ha sido auto-generado por `zetteltex init_config`

[general]
# Idioma de la interfaz: es o en
lang = "{}"
# Autor por defecto para \author en nuevas notas y proyectos (vacío: usar el de la plantilla)
author = "{}"
# Editor para el comando edit
editor = "{}"

[render]
# Directorio donde se guardarán los archivos PDF compilados
pdf_output_dir = "{}"
# Directorio donde se guardarán los archivos HTML compilados
html_output_dir = "{}"

[export]
# Ruta a la vault de Obsidian (opcional)
obsidian_vault = "{}"
# Subdirectorio para las notas dentro de obsidian_vault
notes_subdir = "{}"
# Subdirectorio para los proyectos dentro de obsidian_vault
projects_subdir = "{}"

[fuzzy]
# Número máximo de resultados a mostrar en búsquedas
max_results = {}
# Número de resultados a mostrar cuando la búsqueda está vacía (historial + populares)
history_results = {}
# Color de acento de la interfaz (en ANSI, por ejemplo 'blue', 'green', 'magenta')
selection_color = "{}"
"#;
const CONFIG_TOML_EN: &str = r#"# ZettelTeX configuration
# This file was auto-generated by `zetteltex init_config`

[general]
# Interface language: es or en
lang = "{}"
# Default author for \author in new notes and projects (empty: keep the template's)
author = "{}"
# Editor for the edit command
editor = "{}"

[render]
# Directory where compiled PDF files are stored
pdf_output_dir = "{}"
# Directory where compiled HTML files are stored
html_output_dir = "{}"

[export]
# Path to your Obsidian vault (optional)
obsidian_vault = "{}"
# Subdirectory for notes inside obsidian_vault
notes_subdir = "{}"
# Subdirectory for projects inside obsidian_vault
projects_subdir = "{}"

[fuzzy]
# Maximum number of results to show in searches
max_results = {}
# Number of results shown when the search is empty (history + popular)
history_results = {}
# Accent color of the interface (ANSI, e.g. 'blue', 'green', 'magenta')
selection_color = "{}"
"#;

pub fn init_workspace(root: &str) -> Result<()> {
    let root_path = Path::new(root);
    fs::create_dir_all(root_path.join("notes/slipbox"))?;
    fs::create_dir_all(root_path.join("projects"))?;
    let workspace_template = root_path.join("template");
    fs::create_dir_all(&workspace_template)?;

    let docs_path = root_path.join("notes/documents.tex");
    if !docs_path.exists() {
        fs::write(&docs_path, "% zetteltex: documents main index\n")?;
    }

    let template_files = [
        ("note.tex", TEMPLATE_NOTE),
        ("project.tex", TEMPLATE_PROJECT),
        ("style.sty", TEMPLATE_STYLE),
        ("texbook.cls", TEMPLATE_TEXBOOK),
        ("texnote.cls", TEMPLATE_TEXNOTE),
    ];

    for (name, content) in template_files {
        let dst = workspace_template.join(name);
        if !dst.exists() {
            fs::write(dst, content)?;
        }
    }

    println!(
        "{} '{}'",
        tr(
            "Workspace inicializado correctamente en",
            "Workspace initialized successfully at"
        ),
        root
    );
    println!(
        "{}",
        tr!(
            "Directorios creados e inicializados: notes/slipbox, projects, template",
            "Directories created and initialized: notes/slipbox, projects, template"
        )
    );
    Ok(())
}

pub fn read_template_file_or_suggest_init(paths: &WorkspacePaths, name: &str) -> Result<String> {
    let p = paths.template.join(name);
    if !p.exists() {
        eprintln!(
            "{} '{}' {} '{}'. {} `zetteltex --workspace-root {} init` {}.",
            tr("Plantilla", "Template"),
            name,
            tr("no encontrada en", "not found in"),
            paths.template.display(),
            tr("Ejecuta", "Run"),
            paths.root.display(),
            tr("para crear las plantillas", "to create the templates")
        );
        bail!(
            "{}: {}",
            tr("Missing template", "Missing template"),
            p.display()
        );
    }
    let s = fs::read_to_string(&p)?;
    Ok(s)
}

pub fn ensure_template_available_or_suggest_init(paths: &WorkspacePaths) -> Result<()> {
    // Check for at least one of the core template files that TeX needs.
    let candidates = ["texnote.cls", "texbook.cls", "style.sty", "note.tex"];
    for c in candidates {
        if paths.template.join(c).exists() {
            return Ok(());
        }
    }
    eprintln!(
        "{} '{}'. {} `zetteltex --workspace-root {} init` {}.",
        tr(
            "No se encontraron archivos de plantilla en",
            "No template files found in"
        ),
        paths.template.display(),
        tr("Ejecuta", "Run"),
        paths.root.display(),
        tr(
            "para crear las plantillas necesarias",
            "to create the required templates"
        )
    );
    bail!(
        "{}: {}",
        tr("Missing template directory", "Missing template directory"),
        paths.template.display()
    );
}

fn prompt_user(prompt: &str, default: &str) -> anyhow::Result<String> {
    print!("{} [{}]: ", prompt, default);
    std::io::stdout().flush()?;
    let mut input = String::new();
    std::io::stdin().read_line(&mut input)?;
    let trimmed = input.trim();
    if trimmed.is_empty() {
        Ok(default.to_string())
    } else {
        Ok(trimmed.to_string())
    }
}

/// Rellena los placeholders `{}` de la plantilla TOML con cada valor, en orden.
fn render_config_toml(template: &str, values: &[String]) -> String {
    let mut out = String::new();
    let mut rest = template;
    for value in values {
        if let Some(i) = rest.find("{}") {
            out.push_str(&rest[..i]);
            out.push_str(value);
            rest = &rest[i + 2..];
        } else {
            break;
        }
    }
    out.push_str(rest);
    out
}

fn escape_toml_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\t' => out.push_str("\\t"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

pub fn init_config_interactive(paths: &WorkspacePaths) -> anyhow::Result<std::process::ExitCode> {
    let config_path = paths.root.join("zetteltex.toml");

    if config_path.exists() {
        print!(
            "{} (y/N): ",
            tr!(
                "El archivo {} ya existe. ¿Deseas sobrescribirlo?",
                "The file {} already exists. Do you want to overwrite it?",
                config_path.display()
            )
        );
        std::io::stdout().flush()?;
        let mut input = String::new();
        std::io::stdin().read_line(&mut input)?;
        if input.trim().to_lowercase() != "y" {
            println!("{}", tr("Operación cancelada.", "Operation canceled."));
            return Ok(std::process::ExitCode::SUCCESS);
        }
    }

    println!(
        "\n=== {} ===",
        tr(
            "Configuración interactiva de ZettelTeX",
            "Interactive ZettelTeX configuration"
        )
    );
    println!(
        "{}",
        tr!(
            "Pulsa Enter para mantener los valores por defecto.\n",
            "Press Enter to keep the default values.\n"
        )
    );

    let lang = prompt_user(
        tr(
            "Idioma de la interfaz (es|en)",
            "Interface language (es|en)",
        ),
        "en",
    )?;
    let chosen_lang = Lang::parse(&lang);
    set_lang(chosen_lang);
    let editor = prompt_user(
        tr(
            "Editor preferido (code, vim, nvim, o ruta personalizada)",
            "Preferred editor (code, vim, nvim, or custom path)",
        ),
        "code",
    )?;
    let author = prompt_user(
        tr(
            "Autor por defecto para nuevas notas y proyectos (vacío: usar el de la plantilla)",
            "Default author for new notes and projects (empty: keep the template's)",
        ),
        "",
    )?;
    let pdf_output_dir = prompt_user(
        tr(
            "Directorio de salida para PDFs compilados",
            "Output directory for compiled PDFs",
        ),
        "pdf",
    )?;
    let html_output_dir = prompt_user(
        tr(
            "Directorio de salida para HTML compilado",
            "Output directory for compiled HTML",
        ),
        "html",
    )?;
    let obsidian_vault = prompt_user(
        tr(
            "Ruta a tu vault de Obsidian (deja vacío si no usas)",
            "Path to your Obsidian vault (leave empty if unused)",
        ),
        "vault",
    )?;
    let notes_subdir = prompt_user(
        tr(
            "Subdirectorio de notas en la vault",
            "Notes subdirectory in the vault",
        ),
        "notes",
    )?;
    let projects_subdir = prompt_user(
        tr(
            "Subdirectorio de proyectos en la vault",
            "Projects subdirectory in the vault",
        ),
        "projects",
    )?;
    let max_results = prompt_user(
        tr(
            "Número máximo de resultados en búsquedas fuzzy",
            "Maximum number of results in fuzzy searches",
        ),
        "20",
    )?;
    let history_results = prompt_user(
        tr(
            "Número de resultados de historial al abrir fuzzy sin query",
            "Number of history results when opening fuzzy without a query",
        ),
        "20",
    )?;
    let selection_color = prompt_user(
        tr(
            "Color de selección en búsquedas (ej. magenta, blue, green, red)",
            "Selection color in searches (e.g. magenta, blue, green, red)",
        ),
        "magenta",
    )?;

    let lang_value = escape_toml_string(&lang);
    let author_value = escape_toml_string(&author);
    let editor_value = escape_toml_string(&editor);
    let pdf_output_dir_value = escape_toml_string(&pdf_output_dir);
    let html_output_dir_value = escape_toml_string(&html_output_dir);
    let obsidian_vault_value = escape_toml_string(&obsidian_vault);
    let notes_subdir_value = escape_toml_string(&notes_subdir);
    let projects_subdir_value = escape_toml_string(&projects_subdir);
    let selection_color_value = escape_toml_string(&selection_color);

    let values = vec![
        lang_value,
        author_value,
        editor_value,
        pdf_output_dir_value,
        html_output_dir_value,
        obsidian_vault_value,
        notes_subdir_value,
        projects_subdir_value,
        max_results,
        history_results,
        selection_color_value,
    ];
    let config_content = if chosen_lang.is_es() {
        render_config_toml(CONFIG_TOML_ES, &values)
    } else {
        render_config_toml(CONFIG_TOML_EN, &values)
    };

    std::fs::write(&config_path, config_content)?;
    println!(
        "\n{} {}!",
        tr(
            "¡Archivo de configuración guardado exitosamente en",
            "Configuration file saved successfully to"
        ),
        config_path.display()
    );

    Ok(std::process::ExitCode::SUCCESS)
}
